---
collections:
  - name: community.collection

roles:
  - src: https://github.com/kamuridesu/ansible-archlinux-initial-config.git
    scm: git
    name: ansible-role-archlinux-initial-provision/tasks